branch-defaults:
  main:
    environment: dapp-prod
  development: 
    environment: dapp-dev
environment-defaults:
  dapp-prod:
    branch: null
    repository: null
global:
  application_name: jointnft-dapp
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
